module.exports = {
    "rules": {
        "block-scoped-var": 2,
        "consistent-return": 1,
        "curly": 2,
        "dot-notation": 2,
        "eqeqeq": 2,
        "guard-for-in": 2,
        "no-alert": 1,
        "no-caller": 2,
        "no-case-declarations": 1,
        "no-eq-null": 2,
        "no-eval": 2,
        "no-extend-native": 1,
        "no-extra-bind": 2,
        "no-iterator": 1,
        "no-loop-func": 1,
        "no-multi-str": 1,
        "no-new": 0,
        "no-new-func": 2,
        "no-proto": 1,
        "no-redeclare": 2,
        "no-return-assign": 1,
        "no-script-url": 2,
        "no-unused-expressions": 2,
        "no-with": 2,
        "vars-on-top": 1,
        "yoda": 0
    }
};
