module.exports = {
    rules: {
        "block-scoped-var": "error",
        "consistent-return": "warn",
        curly: "error",
        "dot-notation": "error",
        eqeqeq: "error",
        "guard-for-in": "error",
        "no-alert": "warn",
        "no-caller": "error",
        "no-case-declarations": "warn",
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "warn",
        "no-extra-bind": "error",
        "no-iterator": "warn",
        "no-loop-func": "warn",
        "no-multi-str": "warn",
        "no-new": "off",
        "no-new-func": "error",
        "no-proto": "warn",
        "no-redeclare": "error",
        "no-return-assign": "warn",
        "no-script-url": "error",
        "no-unused-expressions": "error",
        "no-with": "error",
        "vars-on-top": "warn",
        yoda: "off"
    }
};
